### ISSUE TITLE
算分发送图片一时时报错

### ISSUE THREAD

**Issue by darkfashi** [ikarosf/nonebot_plugin_gakuenImasCalculator#3]
[error.log](https://github.com/user-attachments/files/17442092/error.log)
这份是log 大佬救救（

**Comment by ikarosf** [comment]
> [error.log](https://github.com/user-attachments/files/17442092/error.log) 这份是log 大佬救救（

这是因为multimedia.nt.qq.com.cn这个域名的国产证书python不支持，所以无法下载QQ聊天图片，似乎必须requests库为2.24.0版本或者urllib3为1.x版本才能正常下载。
由于我这边没有环境修改验证代码，你可以查看以下链接尝试修改
https://github.com/LagrangeDev/Lagrange.Core/issues/315
https://github.com/Soulter/AstrBot/issues/196
https://www.baidu.com/s?ie=UTF-8&wd=multimedia.nt.qq.com%20sslv3%20alert%20handshake%20failure

**Comment by darkfashi** [comment]
好的 我这边尝试一下

**Comment by darkfashi** [comment]
已经解决
顺便问问作者可以update一个算SS的版本吗

**Comment by ikarosf** [comment]
> 已经解决 顺便问问作者可以update一个算SS的版本吗

好的，已做更新。顺便问一下是通过哪个方法解决的

**Comment by darkfashi** [comment]
不好意思 现在才看到 我通过了上面的链接修改了downloadpic添加上ssl的配置就可以了
[downloadpic.txt](https://github.com/user-attachments/files/17484057/downloadpic.txt)
由于git原因我将代码改为txt发送出来（x

**Comment by ikarosf** [comment]
谢谢！
