### ISSUE TITLE
关于算分的代码，似乎有点问题？

### ISSUE THREAD

**Issue by DreamGallery** [ikarosf/nonebot_plugin_gakuenImasCalculator#4]
我看到增加SS算分之后把各级score=-1的赋值给删除了，底下通过score==-1判断很难达到某一评价的逻辑就失效了
另外SS算分的代码的判断变量还是Spscore，是不是直接复制了S+的代码🤣
```
 if Spscore == -1:
        retmessage += ""
    elif Spscore == 0:
        retmessage += "已经稳S+了？？没关就是开了？\n"
    else:
        retmessage += "S+评价需要获得" + str(Spscore) + "分\n"

    if Spscore == -1:
        retmessage += ""
    elif Spscore == 0:
        retmessage += "已经稳SS了？？？你这是在做梦吧？"
    else:
        retmessage += "SS评价需要获得" + str(SSscore) + "分"

    return retmessage
```

**Comment by ikarosf** [comment]
> 我看到增加SS算分之后似乎把各级score=-1的赋值给删除了，底下通过score==-1判断很难达到某一评价的逻辑似乎就失效了 另外SS算分的代码的判断变量还是Spscore，是不是直接复制了S+的代码🤣
> 


因为删卡流可以达到超级高的打分，所以干脆删除了达到某一评价需求分数过高的逻辑
至于SS算分的代码，确实是直接复制忘了改了🤣不过因为在第一个分支中已经删除了需求分数过高的逻辑，在第二个分支中目前又不可能稳S+，所以使用Spscore 判断完全不影响算分结果
属于是该机器人运行于bug之上，从结果上来说算分完全正确，以至于用了这么久没发现有bug
等下次有影响再修改吧

**Comment by DreamGallery** [comment]
还行😂
我这边就把==-1的判断条件换成>=50000/100000/150000/200000这种数值了，也是可以的
